// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Ad-hoc code signing for Mach-O binaries.
///
/// Appending a snapshot to `dartaotruntime` invalidates the signature it
/// shipped with, and macOS on arm64 refuses to execute a binary whose signature
/// does not verify. On a macOS host the SDK fixes that by running Apple's
/// `codesign`; this library does the same job in Dart so that
/// `dart compile exe --target-os macos` also works on hosts that have no
/// `codesign` to run.
///
/// Only ad-hoc signatures are produced: there is no identity, no CMS blob, and
/// no chain of trust. That is enough for the kernel to load the binary, which
/// is what the SDK needs. Distributing a binary still wants a real Developer ID
/// signature and notarization.
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;

/// Blob magics, from `cs_blobs.h`.
const _magicEmbeddedSignature = 0xfade0cc0;
const _magicCodeDirectory = 0xfade0c02;
const _magicRequirements = 0xfade0c01;
const _magicBlobWrapper = 0xfade0b01;

/// Slot numbers within an embedded signature superblob.
const _slotCodeDirectory = 0;
const _slotRequirements = 2;
const _slotCmsSignature = 0x10000;

/// The highest special (negative-indexed) slot we fill. Slot 1 is the info
/// plist, which a bare executable does not have, so it is hashed as zeroes.
const _highestSpecialSlot = _slotRequirements;

/// `CS_ADHOC`: the signature carries no identity.
///
/// This is the only flag set. In particular `CS_RUNTIME` is *not* carried over
/// from the signature being replaced, matching `codesign -f -s -`, which only
/// opts into the hardened runtime when asked with `-o runtime`. Under the
/// hardened runtime a process may not execute memory that no signature covers,
/// and loading an AOT snapshot does exactly that: the runtime allocates pages,
/// writes the snapshot's instructions into them and marks them executable. A
/// dartaotruntime that carries `com.apple.security.cs.allow-unsigned-executable
/// -memory` survives it; one that does not is killed by the kernel with
/// CODESIGNING / "Invalid Page" the moment it enters that memory.
const _flagAdhoc = 0x00000002;

/// `CS_LINKER_SIGNED`: the signature was generated by the toolchain rather than
/// by a developer, and may be replaced without `codesign -f`. The macOS path
/// asks for it with `-o linker-signed` for exactly that reason, so we set it
/// too.
const _flagLinkerSigned = 0x00020000;

/// SHA-256, the only digest modern macOS accepts as primary.
const _hashTypeSha256 = 2;
const _hashSize = 32;

/// Code pages are hashed in units of the target's native page size, matching
/// what `codesign` picks: 16 KiB on arm64, 4 KiB elsewhere. The field stores
/// the log2.
const _pageSizeLog2Arm64 = 14;
const _pageSizeLog2Default = 12;

/// The code directory layout we emit, matching what `codesign` writes for an
/// ad-hoc signature. 0x20400 carries the `execSeg*` fields that describe the
/// executable segment to the kernel; 0x20500 would only add `runtime`, which is
/// meaningless without the hardened runtime.
const _codeDirectoryVersion = 0x20400;
const _codeDirectoryHeaderSize = 88;

const _lcSegment64 = 0x19;
const _lcCodeSignature = 0x1d;
const _lcUuid = 0x1b;

/// `CPU_TYPE_ARM64`, i.e. `CPU_TYPE_ARM | CPU_ARCH_ABI64`.
const _cpuTypeArm64 = 0x0100000c;

/// `CS_EXECSEG_MAIN_BINARY`, set on the executable segment of a main binary.
const _execSegMainBinary = 0x1;

/// Signs [file] in place with an ad-hoc signature.
///
/// The file must already contain an `LC_CODE_SIGNATURE` load command; the
/// region it points at is rewritten. Nothing is carried over from the signature
/// being replaced.
///
/// [identifier] defaults to the file's base name plus a suffix derived from
/// `LC_UUID`, which is how the linker names a binary it signs itself.
void adHocSignMachO(File file, {String? identifier}) {
  final bytes = file.readAsBytesSync();
  final signed = adHocSignMachOBytes(
    bytes,
    identifier: identifier,
    name: p.basenameWithoutExtension(file.path),
  );
  file.writeAsBytesSync(signed, flush: true);
}

/// The [adHocSignMachO] transformation as a pure function, so it can be tested
/// without touching the file system.
Uint8List adHocSignMachOBytes(
  Uint8List bytes, {
  String? identifier,
  String name = 'a.out',
}) {
  final macho = _MachO.parse(bytes);
  final signature = macho.codeSignatureCommand;
  if (signature == null) {
    throw const FormatException(
      'Mach-O has no LC_CODE_SIGNATURE load command to replace. Reserving '
      'space for one is the linker\'s job, so this binary cannot be signed '
      'after the fact.',
    );
  }
  final linkEdit = macho.linkEditSegment;
  if (linkEdit == null) {
    throw const FormatException('__LINKEDIT segment not found');
  }

  // Everything up to the signature is what gets hashed. The signature always
  // sits last, so this is also where the old blob started.
  final codeLimit = signature.dataOffset;
  final previous = _EmbeddedSignature.parse(
    bytes,
    codeLimit,
    signature.dataSize,
  );

  // Nothing is carried over from the signature being replaced, which is what
  // `codesign -f -s -` does and what a macOS-hosted `dart compile exe`
  // therefore produces: an empty requirement set, no entitlements, no flags
  // beyond ad-hoc.
  //
  // Each of those would be a claim the new signature cannot back. The
  // requirement set designates "anchor apple generic and certificate leaf
  // subject.OU = <team>", which an ad-hoc signature can never satisfy. The
  // entitlements are hardened-runtime opt-outs plus, on some builds,
  // get-task-allow; without the hardened runtime they grant nothing.
  final requirements = _emptyRequirementSet();

  // `ld` names a binary it signs "<name>-<hex of \"UUID\" + LC_UUID>", and
  // `codesign -o linker-signed` keeps that shape. Without an LC_UUID there is
  // nothing to derive from, so fall back to the bare name.
  final uuid = macho.uuid;
  final derivedIdentifier =
      identifier ??
      (uuid == null ? name : '$name-${_hex([...'UUID'.codeUnits, ...uuid])}');

  // Sizes have to be settled before hashing: the load commands we are about to
  // rewrite live inside the hashed range, so the digests must be taken after
  // the final `datasize` and `filesize` values are in place.
  final pageSizeLog2 = macho.isArm64
      ? _pageSizeLog2Arm64
      : _pageSizeLog2Default;
  final pageSize = 1 << pageSizeLog2;
  final codeSlots = (codeLimit + pageSize - 1) ~/ pageSize;
  final identifierBytes = Uint8List.fromList([
    ...derivedIdentifier.codeUnits,
    0,
  ]);
  final codeDirectoryLength =
      _codeDirectoryHeaderSize +
      identifierBytes.length +
      (_highestSpecialSlot + codeSlots) * _hashSize;

  final blobs = <int, int>{
    _slotCodeDirectory: codeDirectoryLength,
    _slotRequirements: requirements.length,
    _slotCmsSignature: 8,
  };
  final superBlobLength =
      12 + 8 * blobs.length + blobs.values.fold<int>(0, (a, b) => a + b);
  // Reuse the signature area the linker reserved when the new signature fits,
  // so that neither the end of __LINKEDIT nor the end of the file moves. Only
  // when it does not fit do we resize.
  //
  // `codesign` instead shrinks the area to its own estimate (measured: a 56256
  // byte reserve came back as 29392 for an 11392 byte signature), so our output
  // keeps more zero padding than a macOS-hosted build. The padding is inert.
  final dataSize = signature.dataSize >= superBlobLength
      ? signature.dataSize
      : _roundUp(superBlobLength, 16);

  final output = Uint8List(codeLimit + dataSize)..setRange(0, codeLimit, bytes);

  // Patch the sizes into the copy that is about to be hashed.
  _writeUint32(output, signature.dataSizeOffset, dataSize, macho.endian);
  _writeUint64(
    output,
    linkEdit.fileSizeOffset,
    codeLimit + dataSize - linkEdit.fileOffset,
    macho.endian,
  );
  _writeUint64(
    output,
    linkEdit.vmSizeOffset,
    _roundUp(codeLimit + dataSize - linkEdit.fileOffset, pageSize),
    macho.endian,
  );

  final codeDirectory = _buildCodeDirectory(
    image: output,
    identifier: identifierBytes,
    codeLimit: codeLimit,
    codeSlots: codeSlots,
    pageSizeLog2: pageSizeLog2,
    length: codeDirectoryLength,
    flags: _flagAdhoc | _flagLinkerSigned,
    platform: previous?.platform ?? 0,
    execSegBase: previous?.execSegBase ?? macho.textSegmentFileOffset ?? 0,
    execSegLimit: previous?.execSegLimit ?? macho.textSegmentFileSize ?? 0,
    execSegFlags: previous?.execSegFlags ?? _execSegMainBinary,
    specialSlots: {_slotRequirements: requirements},
  );

  final superBlob = _buildSuperBlob({
    _slotCodeDirectory: codeDirectory,
    _slotRequirements: requirements,
    _slotCmsSignature: _emptyBlobWrapper(),
  });
  assert(superBlob.length == superBlobLength);
  output.setRange(codeLimit, codeLimit + superBlob.length, superBlob);

  return output;
}

Uint8List _buildCodeDirectory({
  required Uint8List image,
  required Uint8List identifier,
  required int codeLimit,
  required int codeSlots,
  required int pageSizeLog2,
  required int length,
  required int flags,
  required int platform,
  required int execSegBase,
  required int execSegLimit,
  required int execSegFlags,
  required Map<int, Uint8List> specialSlots,
}) {
  final cd = Uint8List(length);
  final data = ByteData.sublistView(cd);

  final identifierOffset = _codeDirectoryHeaderSize;
  // Slot 0 is the first code page; the special slots are stored ahead of it,
  // highest slot number first, so index -n lands at hashOffset - n * hashSize.
  final hashOffset =
      identifierOffset + identifier.length + _highestSpecialSlot * _hashSize;

  data.setUint32(0, _magicCodeDirectory);
  data.setUint32(4, length);
  data.setUint32(8, _codeDirectoryVersion);
  data.setUint32(12, flags);
  data.setUint32(16, hashOffset);
  data.setUint32(20, identifierOffset);
  data.setUint32(24, _highestSpecialSlot);
  data.setUint32(28, codeSlots);
  data.setUint32(32, codeLimit);
  data.setUint8(36, _hashSize);
  data.setUint8(37, _hashTypeSha256);
  data.setUint8(38, platform);
  data.setUint8(39, pageSizeLog2);
  // spare2 (40), scatterOffset (44), teamOffset (48), spare3 (52) stay zero:
  // ad-hoc signatures have no scatter vector and no team id.
  data.setUint64(56, 0); // codeLimit64, only used past 4 GiB.
  data.setUint64(64, execSegBase);
  data.setUint64(72, execSegLimit);
  data.setUint64(80, execSegFlags);

  cd.setRange(
    identifierOffset,
    identifierOffset + identifier.length,
    identifier,
  );

  for (final entry in specialSlots.entries) {
    final offset = hashOffset - entry.key * _hashSize;
    cd.setRange(offset, offset + _hashSize, sha256.convert(entry.value).bytes);
  }

  final pageSize = 1 << pageSizeLog2;
  for (var slot = 0; slot < codeSlots; slot++) {
    final start = slot * pageSize;
    final end = start + pageSize > codeLimit ? codeLimit : start + pageSize;
    final offset = hashOffset + slot * _hashSize;
    cd.setRange(
      offset,
      offset + _hashSize,
      sha256.convert(Uint8List.sublistView(image, start, end)).bytes,
    );
  }

  return cd;
}

Uint8List _buildSuperBlob(Map<int, Uint8List> blobs) {
  final length =
      12 + 8 * blobs.length + blobs.values.fold<int>(0, (a, b) => a + b.length);
  final out = Uint8List(length);
  final data = ByteData.sublistView(out);

  data.setUint32(0, _magicEmbeddedSignature);
  data.setUint32(4, length);
  data.setUint32(8, blobs.length);

  var indexOffset = 12;
  var blobOffset = 12 + 8 * blobs.length;
  for (final entry in blobs.entries) {
    data.setUint32(indexOffset, entry.key);
    data.setUint32(indexOffset + 4, blobOffset);
    out.setRange(blobOffset, blobOffset + entry.value.length, entry.value);
    indexOffset += 8;
    blobOffset += entry.value.length;
  }
  return out;
}

/// An empty requirement set: the binary states no designated requirement, which
/// is the correct thing for a signature with no identity to bind to.
Uint8List _emptyRequirementSet() {
  final out = Uint8List(12);
  ByteData.sublistView(out)
    ..setUint32(0, _magicRequirements)
    ..setUint32(4, 12)
    ..setUint32(8, 0);
  return out;
}

/// An empty CMS wrapper. Present but empty is what "ad-hoc" means on the wire.
Uint8List _emptyBlobWrapper() {
  final out = Uint8List(8);
  ByteData.sublistView(out)
    ..setUint32(0, _magicBlobWrapper)
    ..setUint32(4, 8);
  return out;
}

String _hex(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

int _roundUp(int value, int alignment) =>
    (value + alignment - 1) ~/ alignment * alignment;

void _writeUint32(Uint8List bytes, int offset, int value, Endian endian) =>
    ByteData.sublistView(bytes).setUint32(offset, value, endian);

void _writeUint64(Uint8List bytes, int offset, int value, Endian endian) =>
    ByteData.sublistView(bytes).setUint64(offset, value, endian);

/// The previous embedded signature, read for the parts worth carrying over.
class _EmbeddedSignature {
  final Map<int, Uint8List> _blobs;
  final int platform;
  final int execSegBase;
  final int execSegLimit;
  final int execSegFlags;

  _EmbeddedSignature._(
    this._blobs,
    this.platform,
    this.execSegBase,
    this.execSegLimit,
    this.execSegFlags,
  );

  Uint8List? blob(int slot) => _blobs[slot];

  /// Returns null when the region does not hold a signature we understand, in
  /// which case the caller signs from scratch rather than failing.
  static _EmbeddedSignature? parse(Uint8List bytes, int offset, int size) {
    if (offset + size > bytes.length || size < 12) return null;
    final data = ByteData.sublistView(bytes, offset, offset + size);
    if (data.getUint32(0) != _magicEmbeddedSignature) return null;

    final count = data.getUint32(8);
    final blobs = <int, Uint8List>{};
    for (var i = 0; i < count; i++) {
      final indexOffset = 12 + 8 * i;
      if (indexOffset + 8 > size) return null;
      final slot = data.getUint32(indexOffset);
      final blobOffset = data.getUint32(indexOffset + 4);
      if (blobOffset + 8 > size) return null;
      final blobLength = data.getUint32(blobOffset + 4);
      if (blobOffset + blobLength > size) return null;
      blobs[slot] = Uint8List.sublistView(
        bytes,
        offset + blobOffset,
        offset + blobOffset + blobLength,
      );
    }

    var platform = 0;
    var execSegBase = 0;
    var execSegLimit = 0;
    var execSegFlags = 0;
    final cd = blobs[_slotCodeDirectory];
    if (cd != null && cd.length >= 40) {
      final cdData = ByteData.sublistView(cd);
      final version = cdData.getUint32(8);
      platform = cdData.getUint8(38);
      if (version >= 0x20400 && cd.length >= 88) {
        execSegBase = cdData.getUint64(64);
        execSegLimit = cdData.getUint64(72);
        execSegFlags = cdData.getUint64(80);
      }
    }

    return _EmbeddedSignature._(
      blobs,
      platform,
      execSegBase,
      execSegLimit,
      execSegFlags,
    );
  }
}

/// Just enough Mach-O parsing to find the two load commands we rewrite, and
/// where their size fields sit in the file.
class _MachO {
  final Endian endian;
  final int cpuType;
  final _LinkeditDataCommand? codeSignatureCommand;
  final _SegmentCommand? linkEditSegment;
  final int? textSegmentFileOffset;
  final int? textSegmentFileSize;
  final Uint8List? uuid;

  _MachO._(
    this.endian,
    this.cpuType,
    this.codeSignatureCommand,
    this.linkEditSegment,
    this.textSegmentFileOffset,
    this.textSegmentFileSize,
    this.uuid,
  );

  bool get isArm64 => cpuType == _cpuTypeArm64;

  static _MachO parse(Uint8List bytes) {
    if (bytes.length < 32) {
      throw const FormatException('file is too short to be a Mach-O binary');
    }
    final data = ByteData.sublistView(bytes);
    final magic = data.getUint32(0, Endian.little);
    final Endian endian;
    if (magic == 0xfeedfacf) {
      endian = Endian.little;
    } else if (magic == 0xcffaedfe) {
      endian = Endian.big;
    } else {
      throw FormatException(
        'not a 64-bit Mach-O binary (magic 0x${magic.toRadixString(16)}); '
        'ad-hoc signing of 32-bit or universal binaries is not supported',
      );
    }

    final cpuType = data.getUint32(4, endian);
    final commandCount = data.getUint32(16, endian);
    Uint8List? uuid;
    _LinkeditDataCommand? signature;
    _SegmentCommand? linkEdit;
    int? textOffset;
    int? textSize;

    var offset = 32;
    for (var i = 0; i < commandCount; i++) {
      if (offset + 8 > bytes.length) {
        throw const FormatException('load commands run past end of file');
      }
      final command = data.getUint32(offset, endian);
      final commandSize = data.getUint32(offset + 4, endian);
      if (commandSize < 8 || offset + commandSize > bytes.length) {
        throw const FormatException('malformed load command');
      }
      switch (command) {
        case _lcCodeSignature:
          signature = _LinkeditDataCommand(
            data.getUint32(offset + 8, endian),
            data.getUint32(offset + 12, endian),
            offset + 12,
          );
        case _lcSegment64:
          final name = _readName(bytes, offset + 8);
          if (name == '__LINKEDIT') {
            linkEdit = _SegmentCommand(
              data.getUint64(offset + 40, endian),
              offset + 48,
              offset + 32,
            );
          } else if (name == '__TEXT') {
            textOffset = data.getUint64(offset + 40, endian);
            textSize = data.getUint64(offset + 48, endian);
          }
        case _lcUuid:
          if (commandSize >= 24) {
            uuid = Uint8List.sublistView(bytes, offset + 8, offset + 24);
          }
      }
      offset += commandSize;
    }

    return _MachO._(
      endian,
      cpuType,
      signature,
      linkEdit,
      textOffset,
      textSize,
      uuid,
    );
  }

  static String _readName(Uint8List bytes, int offset) {
    var end = offset;
    while (end < offset + 16 && bytes[end] != 0) {
      end++;
    }
    return String.fromCharCodes(bytes, offset, end);
  }
}

class _LinkeditDataCommand {
  final int dataOffset;
  final int dataSize;

  /// Where `datasize` lives in the file, so it can be rewritten in place.
  final int dataSizeOffset;

  _LinkeditDataCommand(this.dataOffset, this.dataSize, this.dataSizeOffset);
}

class _SegmentCommand {
  final int fileOffset;

  /// Where `filesize` and `vmsize` live in the file.
  final int fileSizeOffset;
  final int vmSizeOffset;

  _SegmentCommand(this.fileOffset, this.fileSizeOffset, this.vmSizeOffset);
}
